### ISSUE TITLE
Yo please help, would love to text on your tele handle 

### ISSUE THREAD

**Issue by sketchycarder** [OfficialCodeVoyage/GitHub_Follower_Bot_Automated#4]
ENOENT: no such file or directory, stat 'E:\pinokio\api\photomaker2.git{{input.event[0]}}'comfy ui on pinokio, after installing and all it keep saying this and wont open, I tried live portrait it’s asking the me to choose yes or no if it should download the new file and existing some because I’ve been trying over and over but it won’t show me a key or option to input the command. Any other ai tool on pinokio won’t work on my HP laptop. Please help what do I do

**Comment by OfficialCodeVoyage** [comment]
I don't think it relates to this project!

**Comment by OfficialCodeVoyage** [comment]
I don't think it relates to this project!
